version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: '10:00'
  open-pull-requests-limit: 10