- id: django-upgrade
  name: django-upgrade
  description: Automatically upgrade your Django project code.
  entry: django-upgrade
  language: python
  types: [python]
  # for backward compatibility
  files: ''
  minimum_pre_commit_version: 0.15.0