#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$PATH
GRAPHITE_PATH=/opt/graphite

python ${GRAPHITE_PATH}/webapp/graphite/manage.py syncdb --noinput

chown -R apache.apache ${GRAPHITE_PATH}/storage
chown -R apache.apache ${GRAPHITE_PATH}/webapp
